name: bandora_app
description: A new Flutter project.

publish_to: "none"

version: 2.0.5+4

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  intl_phone_field: ^3.2.0
  pinput: ^3.0.1
  carousel_slider: ^5.0.0
  dotted_border: ^2.1.0
  google_fonts: ^4.0.4
  http: ^0.13.6
  either_dart: ^0.4.0
  shimmer: ^3.0.0
  flutter_svg: ^2.0.5
  lottie: ^2.3.2
  flutter_secure_storage: ^9.2.4
  get_storage: ^2.1.1
  persistent_bottom_nav_bar: ^6.2.1
  timeline_tile: ^2.0.0
  rename: ^3.0.1
  slide_countdown: ^0.6.0
  url_launcher: ^6.1.11
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  google_maps_flutter: ^2.5.3
  upgrader: ^8.4.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  firebase_crashlytics: ^3.4.9
  firebase_analytics: ^10.8.0
  cloud_firestore: ^4.14.0
  flutter_rating_bar: ^4.0.0
  flutter_local_notifications: ^18.0.1
  flutter_bloc: ^8.1.3
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  json_serializable: ^6.8.0
  json_annotation: ^4.8.1
  dio: ^5.3.3
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.4
  pretty_dio_logger: ^1.3.1
  intl: ^0.19.0
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.3
  connectivity_plus: ^6.0.5
  flutter_dotenv: ^5.1.0
  animate_do: ^3.3.4
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.8
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  pusher_channels_flutter: ^2.4.0





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/sme_logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/sme_logo.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#F0E6C3"
  image: "assets/images/sme_logo.png"
  android: true
  ios: true
  android_12:
    image: "assets/images/sme_logo.png"
    color: "#F0E6C3"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/orders/
    - assets/icons/
    - assets/lottie/

  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo/Cairo-Regular.ttf
